name = "sat-water-temps"
pages_build_output_dir = "public"
compatibility_date = "2025-12-11"

# R2 bindings for Pages Functions
# Using production bucket for both dev and prod for now
[[r2_buckets]]
binding = "R2_DATA"
bucket_name = "multitifs"
preview_bucket_name = "multitifs"
remote = true
