#!/bin/bash
# Fetch Cognito credentials from Terraform and create .dev.vars for local development

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

cd "$PROJECT_ROOT/terraform"

echo "Fetching Cognito credentials from Terraform..."

# Check if terraform state exists
if ! terraform state list &>/dev/null; then
    echo "Error: No Terraform state found. Run 'terraform apply' first."
    exit 1
fi

# Fetch values
USER_POOL_ID=$(terraform output -raw cognito_user_pool_id 2>/dev/null)
CLIENT_ID=$(terraform output -raw cognito_client_id 2>/dev/null)
CLIENT_SECRET=$(terraform output -raw cognito_client_secret 2>/dev/null)
SESSION_SECRET=$(terraform output -raw session_secret 2>/dev/null)

if [ -z "$USER_POOL_ID" ] || [ -z "$CLIENT_ID" ]; then
    echo "Error: Could not fetch Cognito outputs. Ensure Cognito resources are deployed."
    exit 1
fi

# Write .dev.vars
DEV_VARS_PATH="$PROJECT_ROOT/.dev.vars"

cat > "$DEV_VARS_PATH" << EOF
# Auto-generated by scripts/setup-dev-auth.sh
# Do not commit this file (it's in .gitignore)

COGNITO_USER_POOL_ID=$USER_POOL_ID
COGNITO_CLIENT_ID=$CLIENT_ID
COGNITO_CLIENT_SECRET=$CLIENT_SECRET
COGNITO_REGION=ap-southeast-1
SESSION_SECRET=$SESSION_SECRET
AUTH_SECRET=$SESSION_SECRET
EOF

echo "Created .dev.vars with Cognito credentials"
echo "Run 'npm run wrangler:dev' to start local development with auth"
